apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myhttpd1
  template:
    metadata:
      labels:
        app: myhttpd1
    spec:
      containers:
      - name: ip-pod
        image: oolralra/ipnginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ip
spec:
  type: NodePort
  selector:
    app: myhttpd1
  ports:
  - nodePort: 32001
    port: 80
    targetPort: 80
